language: java
jdk:
#  - openjdk6
#  - oraclejdk7
#  - openjdk7
  - oraclejdk8
  - oraclejdk9

before_install:
  # workaroud for "buffer overflow detected" problem of openjdk:
  #     https://github.com/travis-ci/travis-ci/issues/5227
  # borrow from https://github.com/miguno/kafka-storm-starter/blob/01dd534263eb867304c06cd2a72f640da1bd9367/.travis.yml
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

  # output env info
  - ls -l /usr/lib/jvm
  - echo "JAVA_HOME=$JAVA_HOME"
  - echo "PATH=$PATH"
  - mvn --version

  - pip install --user codecov

script:
  - mvn test -B
  - ./run-agent-test.sh skip

after_success:
  - codecov

# cache between builds
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
