# appveyor.yml Reference
# https://www.appveyor.com/docs/appveyor-yml/
#
# How to use AppVeyor to build a multi-arch Docker image for Linux and Windows
# https://stefanscherer.github.io/use-appveyor-to-build-multi-arch-docker-image/
#
# Building ASP.NET Core apps on both Windows and Linux using AppVeyor
# https://andrewlock.net/building-asp-net-core-apps-on-both-windows-and-linux-using-appveyor/
#
# appveyor.yml Example:
# https://github.com/cdcseacave/openMVS/blob/master/.appveyor.yml

version: '{build}'
image: Ubuntu2004
build: false
clone_depth: 50
branches:
  except:
    - gh-pages

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  MAVEN_OPTS: "-Xmx768m -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2"
  JAVA_OPTS: "-Xmx768m"

install:
  - git submodule update --init

test_script:
  - scripts/integration-test.sh

after_test:
  - scripts/codecov.sh -s
  # remove self maven install
  - rm -rf $HOME/.m2/repository/com/alibaba/transmittable-thread-local*
  - rm -rf $HOME/.m2/repository/com/alibaba/ttl*
  # remove maven install file
  - rm -rf $HOME/.m2/wrapper/dists/*/*/*.zip
  # # remove sdkman install file
  - rm -rf $HOME/.sdkman/archives/*

cache:
  # if cache size is exceed appveyor limit:
  #   Compressed cache item cannot exceed 1,048,576,000 bytes
  # skip below maven cache:
  - $HOME/.m2/
  - $HOME/.sdkman/
